apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-dittoserver-editor-role
  labels:
    {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - dittofs.dittofs.com
  resources:
  - dittoservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dittofs.dittofs.com
  resources:
  - dittoservers/status
  verbs:
  - get
