## DittoFS Operator sample configurations ##
resources:
  - ditto.io_v1alpha1_dittoserver.yaml
  - dittofs_v1alpha1_dittofs_memory.yaml
  - dittofs_v1alpha1_dittoserver_percona.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
